import { Rdl as ARJS, PageReport } from "@grapecity/activereports/core";
import { PdfExport } from "@grapecity/activereports";

export function buildReportDefinition() {
    const report = {};
    report.Width = "8.5in";
    report.Page = {
        TopMargin: "0.5in",
        BottomMargin: "0.5in",
        LeftMargin: "0.5in",
        RightMargin: "0.5in",
        PageWidth: "8.5in",
        PageHeight: "11in",
    };
    const textbox = { Type: "textbox", Name: "txtGreetings" };
    textbox.Value = "Hello, ActiveReportsJS";
    textbox.Style = {
        FontSize: "18pt",
    };
    textbox.Width = "7in";
    textbox.Height = "0.5in";
    report.Body = { ReportItems: [textbox, textbox] };
    return report;
}

export async function exportReport(
    reportDefinition
) {
    const pageReport = new PageReport();
    await pageReport.load(reportDefinition);
    const doc = await pageReport.run();
    return PdfExport.exportDocument(doc, {
        info: {
            title: "Generated by ActiveReportsJS",
        },
    });
}